# Generated by Django 6.1 on 2026-08-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('month', models.DateField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budgets.scenario')),
            ],
            options={
                'ordering': ['department', 'category', 'month'],
            },
        ),
    ]
