# Generated by Django 6.1 on 2026-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
